server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 # pay_routh      # 路由的ID（类似mysql主键id），没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service      # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**    # 断言，路径相匹配的进行路由
#            - After=2025-06-06T18:47:00.855472+08:00[Asia/Shanghai]
#            - Before=2025-06-06T18:50:00.855472+08:00[Asia/Shanghai]
#            - Between=2025-06-06T18:50:00.855472+08:00[Asia/Shanghai],2025-06-06T18:52:00.855472+08:00[Asia/Shanghai]
#            - Cookie=username,rex
#            - Header=X-Request-Id, \d+
#            - Host=**.rexhub.space
#            - Query=username, \d+
#            - RemoteAddr=192.168.0.1/24
#            - Method=POST
#            - My=diamond
#            - name: My
#              args:
#                userType: diamond
        - id: pay_routh2 # pay_routh2     # 路由的ID（类似mysql主键id），没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service      # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**   # 断言，路径相匹配的进行路由
        - id: pay_routh3 # pay_routh3     # 路由的ID（类似mysql主键id），没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service      # 匹配后提供服务的路由地址
          predicates:
             - Path=/pay/gateway/filter/**   # 断言，路径相匹配的进行路由
#             - Path=/gateway/filter/**   # 断言，路径相匹配的进行路由
#             - Path=/XYZ/abc/{segment}   # 断言，路径相匹配的进行路由
          filters:
#            - AddRequestHeader=X-Request-rex1, test1   # 添加请求头
#            - AddRequestHeader=X-Request-rex2, test2   # 添加请求头
#            - RemoveRequestHeader=sec-fetch-site  # 删除请求头
#            - SetRequestHeader=sec-fetch-mode, update   # 设置请求头
#            - AddRequestParameter=customerId, 123456   # 添加请求参数
#            - RemoveRequestParameter=customerName  # 删除请求参数
#            - AddResponseHeader=X-Response-rex, test   # 添加响应头
#            - SetResponseHeader=Date, 2099-11-11 # 设置响应头
#            - RemoveResponseHeader=Content-Type # 删除响应头
#            - PrefixPath=/pay # http://localhost:9527/pay/gateway/filter 被拆分为Prefix+path
#            - SetPath=/pay/gateway/{segment} # http://localhost:9527/XYZ/abc/filter
#            - RedirectTo=302, http://www.baidu.com   # 重定向到指定地址
            - My=rex