server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848 # 配置Nacos
    sentinel:
      transport:
        dashboard: localhost:8080 # 配置sentinel dashboard控制台服务地址
        port: 8719 # 默认8719，假如被占用会自动从8719开始依次+1扫描，直到找到未被占用的端口